# Generated by Django 6.0.5 on 2026-06-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_fr', models.CharField(max_length=200, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم (AR)')),
                ('name_nl', models.CharField(blank=True, max_length=200, verbose_name='Naam (NL)')),
                ('name_de', models.CharField(blank=True, max_length=200, verbose_name='Name (DE)')),
                ('name_es', models.CharField(blank=True, max_length=200, verbose_name='Nombre (ES)')),
                ('icon', models.CharField(default='fas fa-folder', help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name_fr'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('service_type', models.CharField(choices=[('general', 'Renseignements généraux'), ('results', "Résultats d'analyses"), ('appointment', 'Prise de rendez-vous'), ('partnership', 'Partenariat'), ('complaint', 'Réclamation'), ('other', 'Autre')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Laboratoire International', max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title_fr', models.CharField(max_length=300, verbose_name='Titre (FR)')),
                ('excerpt_fr', models.TextField(blank=True, max_length=500, verbose_name='Extrait (FR)')),
                ('content_fr', models.TextField(verbose_name='Contenu (FR)')),
                ('meta_title_fr', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (FR)')),
                ('meta_description_fr', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (FR)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Title (EN)')),
                ('excerpt_en', models.TextField(blank=True, max_length=500, verbose_name='Excerpt (EN)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (EN)')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (EN)')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (EN)')),
                ('title_ar', models.CharField(blank=True, max_length=300, verbose_name='العنوان (AR)')),
                ('excerpt_ar', models.TextField(blank=True, max_length=500, verbose_name='مقتطف (AR)')),
                ('content_ar', models.TextField(blank=True, verbose_name='المحتوى (AR)')),
                ('meta_title_ar', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (AR)')),
                ('meta_description_ar', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (AR)')),
                ('title_nl', models.CharField(blank=True, max_length=300, verbose_name='Titel (NL)')),
                ('excerpt_nl', models.TextField(blank=True, max_length=500, verbose_name='Excerpt (NL)')),
                ('content_nl', models.TextField(blank=True, verbose_name='Inhoud (NL)')),
                ('meta_title_nl', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (NL)')),
                ('meta_description_nl', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (NL)')),
                ('title_de', models.CharField(blank=True, max_length=300, verbose_name='Titel (DE)')),
                ('excerpt_de', models.TextField(blank=True, max_length=500, verbose_name='Auszug (DE)')),
                ('content_de', models.TextField(blank=True, verbose_name='Inhalt (DE)')),
                ('meta_title_de', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (DE)')),
                ('meta_description_de', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (DE)')),
                ('title_es', models.CharField(blank=True, max_length=300, verbose_name='Título (ES)')),
                ('excerpt_es', models.TextField(blank=True, max_length=500, verbose_name='Extracto (ES)')),
                ('content_es', models.TextField(blank=True, verbose_name='Contenido (ES)')),
                ('meta_title_es', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (ES)')),
                ('meta_description_es', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (ES)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
